apiVersion: v1
kind: ResourceQuota
metadata:
  name: cpu-and-mem
spec:
  hard:
    requests.storage: 50Gi
    requests.cpu: 400m
    requests.memory: 200Mi
    limits.cpu: 600m
    limits.memory: 500Mi
    pods: 10 
    replicationcontrollers: 5 
    secrets: 10 
    configmaps: 10 
    persistentvolumeclaims: 4 
    services: 5 
    services.loadbalancers: 1 
    services.nodeports: 2

