apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-default-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /default/nginx-service
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80

